# GitHub Sponsors funding file
# This file is optional and can be removed if not needed

# Uncomment and configure if you want to enable funding
# github: [username]
# patreon: username
# open_collective: username
# ko_fi: username
# tidelift: platform/package-name
# community_bridge: project-name
# liberapay: username
# issuehunt: username
# otechie: username
# lfx_crowdfunding: project-name
# polar: project-name
# buy_me_a_coffee: username
# thanks_dev: username
# custom: ['https://example.com/donate', 'https://another-example.com/donate']

